### ISSUE TITLE
Create a pre-commit hook running linters and link checks

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1003]
It is very easy to commit something and only realise it fails one of our checks after the fact, requiring a second commit to fix minor issues like trailing whitespaces. This can be avoided by remembering to always run our tests before committing, but that's not reliable, especially for new contributors.

Could we set up a [pre-commit hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) that automatically runs these checks when a person tries to commit? Would there be any negatives to this?

@curquiza, perhaps you have some insight on this and whether it's a good idea?

**Comment by curquiza** [comment]
I'm not personally a big fan of commit hook. It can frustrate the users and prevent them from pushing, what we absolutely want to avoid.
Even a bad-formatted PR can be changed directly by the Meili team on the GitHub interface. It's what I do when contributor does not answer: I apply my changes and I merge the PR.
Plus, I think the docs team would rather be informed about a mistake in the docs, even if the PR is not perfect, than not being aware of it at all because the contributor was not able to push.

So I'm not pro this idea. But it's only my opinion.

**Comment by guimachiavelli** [comment]
Yeap, that all sounds very reasonable and I 100% defer to your judgement. 

Thanks for the input!

Marking as won't fix and closing it.
