### ISSUE TITLE
Docs page does not have any 'documentation' which is confusing for new users

### ISSUE THREAD

**Issue by shaloo** [meilisearch/documentation#1355]
Ref: [Current Documentation Index / Landing Page](https://docs.meilisearch.com)

New on-boarders need to know what Meilisearch is before they see sub-heading "Contributing" and "Requirements".  I think the top level docs page needs to be more user friendly.  To find docs, a new user has to know to click 'Learn' ' Resource' menu on top right as there is no link or one line pitch about what Meilisearch is and how it is different on the top of the current index page.

For starters, I'd expect the following: 

MeiliSearch Documentation
----------------------------

This repository is the documentation for the open-source search engine API MeiliSearch (opens new window). 

* [What is MeiliSearch?](https://docs.meilisearch.com/learn/)
* [Getting Started Guide](https://docs.meilisearch.com/learn/getting_started/)
* MeiliSearch Concepts 
  - [Basic](https://docs.meilisearch.com/learn/core_concepts/)
  - [Advanced](https://docs.meilisearch.com/learn/advanced/)
* [CookBooks](https://docs.meilisearch.com/learn/cookbooks/)
* [FAQ](https://docs.meilisearch.com/faq.html)
* [API Documentation](https://docs.meilisearch.com/reference/)
* Resources
  - [OpenAPI](https://docs.meilisearch.com/open-api-readme.html)
  - SDK - list/tabs per language/github link.

Followed by rest of the page content....as is or improvised

Contributing
-------------

Hey, thank you so much for wanting to contribute! If you'd like to help improve this documentation, we'd l

**Comment by dichotommy** [comment]
Hi @shaloo , we have a recurring error on our documentation site where the site builds using `README.md` as the index, instead of the intended homepage, `index.md`. [This is an issue with VuePress](https://github.com/vuejs/vuepress/issues/2106) and likely results from a race condition, so it's difficult to resolve.

If you travel to docs.meilisearch.com now you should see the correct homepage. I hope this helps!
