### ISSUE TITLE
Move `reference/features/language` to `learn/what_is_meilisearch`

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#1373]
As part of our ongoing site restructure, I propose we move the Language guide to `learn/advanced_topics`. 

Possibly not the best place as I don't feel this document is particularly advanced. Happy to hear suggestions of other adequate spots.

**Comment by maryamsulemani97** [comment]
I think we could move it to `learn/what_is_meilisearch` too 🤔

**Comment by dichotommy** [comment]
I agree, it could fit in `learn/what_is_meilisearch` just as well as in `learn/advanced_topics` (which is to say, not particularly well in either location). One thing to note however is that `learn/what_is_meilisearch` is a section I'm hoping to remove entirely once we have a resource center attached to the main website AKA landing page. I just opened an issue about it [here](https://github.com/meilisearch/documentation/issues/1377) so that it's documented. So if it's an article we see ourselves keeping on the docs for a long time, I'd prefer moving it anywhere besides `learn/what_is_meilisearch`.

Is there a world where it makes sense to move this article into `learn/core_concepts`? Not with the current name, I suppose. But if it were renamed something like `Fundamentals` or `Basics`, perhaps.

**Comment by maryamsulemani97** [comment]
If we move it to `learn/core_concepts`, won't it seem out of place with the current pages?

**Comment by guimachiavelli** [comment]
I think the Language article would be really out of place under `learn/core_concepts`. Even if we rename it, the stuff we have in e.g. Documents or Relevancy is information-heavy and educative, whereas Language is really just a quick and friendly reference for MeiliSearch's language support.

I also agree that Language could fit under What is MeiliSearch. My decision to propose Advanced topics was tied to what we mentioned about sticking articles that don't fit anywhere else there (aka our Big Ol' Bag of Random Articles) as a first step towards getting rid of Feature references. Neither What is MeiliSearch nor Advanced topics would be Languages' final resting place.

**Comment by guimachiavelli** [comment]
So, unless anyone fiercely opposes it, I'll continue with moving the Languages guide to Advanced topics.

**Comment by dichotommy** [comment]
Question: is this a page we see ourselves keeping in the docs long-term?

After taking another close look at this page, I feel that this content might be better suited for the resource center—which would mean putting it in `learn/what_is_meilisearch` for now.

For a reference, I look to Algolia: their [language support page](https://support.algolia.com/hc/en-us/articles/4406975245073-Which-languages-are-supported-by-the-engine-) is part of their support website, whereas content on their official documentation related to language is all actionable (e.g. "Multilingual search", "Handling natural languages", "Language-specific configurations", "Set an index's query language").
