### ISSUE TITLE
Documentation sidebar gets triggered while trying to scroll horozontally on tables.

### ISSUE THREAD

**Issue by ChillFish8** [meilisearch/documentation#1402]
- Navigate to https://docs.meilisearch.com/learn/what_is_meilisearch/comparison_to_alternatives.html on a mobile device
- Try to scroll across the table to view additional items
- Observe that about 50% of the time the sidebar will extend out requiring you to tap it away and try scroll again.

**Comment by dichotommy** [comment]
Hey @ChillFish8 , thanks for opening this issue. I wish I could say that we will fix it soon, but I hesitate to promise that. Sadly our site is loaded w/ mobile UX issues like this one, all stemming from VuePress, which is deprecated (or soon to be).

These may be fixed by migration to a different site builder (e.g. [VuePress 2](https://github.com/vuepress/vuepress-next)) or building our own site, but most likely not before then. Again, thanks for bringing it to our attention!

**Comment by guimachiavelli** [comment]
We will release a new docs website in the coming weeks, rendering this issue obsolete.
