### ISSUE TITLE
Logo cut off on mobile

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1403]
Just what the title says

![IMG_5863](https://user-images.githubusercontent.com/68053732/151772941-8d617db4-21c0-4120-bff1-71bdfd0d44a9.PNG)

**Comment by maryamsulemani97** [comment]
Looks fine here

![IMG_FA39667A77CB-1](https://user-images.githubusercontent.com/90181761/151925888-adb63e9d-f139-4ee4-97e8-be2dfe14c638.jpeg)

**Comment by guimachiavelli** [comment]
I think this is more related to screen size than a single mobile browser. Testing on an iphone 12 mini, which AFAIK has one of the narrowest screens commonly available today, I don't even see the logo, just the hamburger menu. I would guess that @dichotommy has a normal-sized iphone and that Maryam has one of the big models (iphone max? plus?).

I'm not sure what can be done in this case. Configuring the logo to resize is probably not going to work out very well because it will look weird if its not always occupying the full menu height. Perhaps we can make the search bar smaller, but that would cause it to be really tiny in a screen like mine.

**Comment by dichotommy** [comment]
> Configuring the logo to resize is probably not going to work out very well because it will look weird if its not always occupying the full menu height. Perhaps we can make the search bar smaller, but that would cause it to be really tiny in a screen like mine.

My first thought was reducing the padding on the search bar. Do you think this could work as a solution?

Otherwise, we might try to trigger dropping the logo (like w/ your iphone 12 mini) at higher screen widths. No logo is better than cut off logo, which just looks unprofesh 😕

**Comment by guimachiavelli** [comment]
The release of the new site renders this issue obsolete.
