### ISSUE TITLE
UI design update to look more consistent with the new branding 

### ISSUE THREAD

**Issue by lpinot** [meilisearch/documentation#1408]
Here is an exemple for the color to change:

H1: pink #FF5CAA
H2: blue #4F55E3
CTA: blue #4F55E3
links: pink #FF5CAA
body-text: dark blue #261A59

<img width="877" alt="Screen Shot 2022-02-01 at 18 16 30" src="https://user-images.githubusercontent.com/83015630/152018853-5db1946b-1502-4aa1-b3ac-285e8ead33a2.png">

Also for the titles, you can use the font Poppins (font-weight: 600)
For the body-text, you can let the font Inter.

**Comment by dichotommy** [comment]
Hi Léna, this looks beautiful! Thanks so much 😊 

The biggest concern with our style is always the color of links: if they're too light or too dark it can impact readability and accessibility. In addition, using the link color for other text types is sometimes seen as a problem (source [NNG Guidelines for Visualizing Links](https://www.nngroup.com/articles/guidelines-for-visualizing-links/): "Never show text in your chosen link colors unless it's a link"). But since it's H1 and we only have one H1 per page (always in the same place), it should not be a problem for us 👌🏻 

I think we should give the color palette you suggested a try and see how it goes. If we feel the link text isn't working well, we can consider darkening the hue as well as underlining links to provide more visual clarity.

I am not the best person to make color-related decisions (#daltonien). WDYT @guimachiavelli @maryamsulemani97 ?

**Comment by maryamsulemani97** [comment]
I really like this! I don’t think the link color will be a problem

**Comment by guimachiavelli** [comment]
Thanks for this, Léna!

I think what Tommy mentions regarding trying not to use the link colour on other elements makes sense as it establishes a quick way for users to group page elements (purple things are titles, pink things are links, etc). To be honest, I do get an instinctive reaction of considering h1 a link, but that might be me being influenced by Tommy's comment.

We can try things out and see how it goes. I'm a fan of underlined links from a usability-focussed perspective, but I would understand if @lpinot pushed back on it and leave the decision to her.

**Comment by bidoubiwa** [comment]
I agree with @dichotommy! Links should have a unique color. But the colors of the documentation are very great :) I would keep the title of the `h1` the same as the other titles. Also it follows the style guidelines of vuepress! I will not have to change any CSS as it is a global variable for all the `h1`

**Comment by bidoubiwa** [comment]
Hey @lpinot could you give me the equivalent dark mode hexa codes ?

**Comment by guimachiavelli** [comment]
>  could you give me the equivalent dark mode hexa codes ?

@bidoubiwa are we going to get a naïve dark mode with `@media(prefers-color-scheme: dark)`? 😍

**Comment by bidoubiwa** [comment]
🙊 (no promises though, there might be unexpected problems)

**Comment by qdequele** [comment]
I close this issue because the design work is finished.
