### ISSUE TITLE
Site title cut off

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#1495]
Adding additional links to the top navbar cuts off the site title

<img width="1280" alt="Screen Shot 2022-03-02 at 16 35 20" src="https://user-images.githubusercontent.com/90181761/156375549-0f3ca31c-7d5f-4b0c-bbf8-f25ad7abb15e.png">

**Comment by guimachiavelli** [comment]
Yeah, there's no easy way out of this one. There's a clear limit to how many links we can fit in a single line, so we either need to remove some of those ("Blog," for instance, is not directly tied to the docs), edit the text (keep "Reference" instead of changing to "API reference", rename "Integrations" to "SDKs"), or reduce text size (might have negative effects on usability).

In a future redesign, we might want to have another dropdown gathering links of relatively low importance. 

Or perhaps we can move a big number of these to the Resource Center, once it arrives?

**Comment by dichotommy** [comment]
Taking a second look at this issue today after @maryamsulemani97 shared her screen during our meeting this morning. On her 13" Macbook, the version number is cut off even when the window is maximized.

As @guimachiavelli said, this is an unavoidable issue. Users of tablets and other screens < 12" in diagonal will always have problems browsing our site so long as we stay with Vuepress 1, which isn't great for responsiveness.

Since our core audience is developers, and 13" is the smallest modern Macbook size, I would suggest that we keep this 13" screen size in mind as the minimum size on which we expect our site to display perfectly. Of course, this would apply only to our current site built on Vuepress; for our next site, we'll aim to display well on all platforms and screen sizes. All in favor?

On this subject, I will open a PR later today to condense some of the top navbar links and hopefully resolve this issue (for screens ≥ 13").
