### ISSUE TITLE
Specify that an identifier is required in schema

### ISSUE THREAD

**Issue by eskombro** [meilisearch/documentation#153]
If an index is created and a schema is provided by the user, it is possible to create an index without specifying any field as an 'identifier'. The problem in that case is that when you try to index data, it will accept the data and provide a modification id, but data is unretrievable afterwards. You don't get any error messages in the process, but can't find the data, which leads to a confusion.

**Comment by curquiza** [comment]
Hi! :)
What is the `modification id`? Is it `updateId` returned by the route `POST index/:index_uid/documents` when you add documents?
Thanks to this `updateId` you can [track your documents addition](https://docs.meilisearch.com/references/updates.html), I mean if it failed or not. Pretty sure that your documents addition failed because you don't provide the right identifier field in your documents.

A thing I've just realized thanks to your issue: if you don't provide any identifier field in the schema during index creation, MeiliSearch add the field `documentId` as a default identifier field. I means that you have to provide a field `documentId` to all the documents you will add.

Another point: the schema might disappear in the next version ;)

**Comment by bidoubiwa** [comment]
Hello !

This was the big issue in the latest version. 
Either, before indexing any document, you define the schema and thus define the identifier field.
Either, in your document, an attribute with the string `id` is present and MeiliSearch will use it as the identifier during document addition.

It is indeed confusing. Because if no attribute is given or if no attribute with `id` inside it is found, no document is indexed and the error provided was no clear as to why.

More can be found here : https://docs.meilisearch.com/guides/main_concepts/indexes.html#inferred-schema

But as @curquiza, the next version will change things up!

**Comment by eskombro** [comment]
Thanks!

Exactly, I meant the updateId.

In my case, after creating an index with a schema (without specifying any 'indentifier' field) and after adding several documents (with no error message and getting updateID as a response to a POST index/:index_uid/documents request, *any search query would return a result with no matches*.

Otherwise, if schema is disappearing soon, this issue may not be pertinent and can be closed!

**Comment by curquiza** [comment]
The point is that the error message you are looking for can be tracked thanks to this route `GET /indexes/:uid/updates/:updateId`. I'm going to detail that:
The route to add documents (the one you used to add data) is asynchronous. That's why MeiliSearch returns an `updateId`. Thanks to this `updateId` you can check if your data have been processed on the queue :)
In other words, on this route, and in your specific case, you would have been seen that your data haven't been processed => that's why you don't get any result for your queries: you don't have any document in Meili :)

**Comment by eskombro** [comment]
Seems completely logical, as it is an asynchronous task. Thanks for the explanation and the feedback!
