### ISSUE TITLE
Quick start button clickable area is too large

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1539]
The clickable area of the quick start button on the [docs homepage](https://docs.meilisearch.com/) extends horizontally past the visual ends of the button to fill the `content-width`.

<img width="1777" alt="Screen Shot 2022-03-22 at 1 22 57 PM" src="https://user-images.githubusercontent.com/68053732/159481529-b2204529-3dd0-4063-b666-a393c48e4878.png">

This is far from the worst thing in the world. The worst case scenario, where a first-time site visitor gets taken to the quick start without meaning to click on it and before they can finish reading content on the homepage, is still just a minor annoyance. Still, this can affect users' opinions about the "professionalism" of our site.

**Comment by guimachiavelli** [comment]
From a quick look, the problem seems to be tied to how the button is centered:

```html
<p>
  <a>
    <div>
      <div>
   </div>
 </div>
</p>
```

`<a>` is wrapping a `<div>` spanning 100% of its parent's width. The easiest solution would be to push `<a>` one level down the tree, but that will cause issues with the button rendering because `<a>` itself does not have `display: block`—this might simple enough to solve by just adding `display: block`, but I'm not sure we have a selector for targeting that specific `<a>`.

**Comment by tobywan-kenobi** [comment]
I've never contributed to an open source project before, but I would like to work on this if possible

**Comment by eugenesimakin** [comment]
Hi folks,

I suggest this #1760 solution. 

There were two options which I considered before implementing this.
- Accessing the parent of `div.route` via CSS. Didn't work because we don't have support for parent CSS selectors.
- Wrapping the `<a>` in a Vue component with some styles. Didn't work because the `.md` extension doesn't get replaced with `.html`.

Hope this helps resolve the issue.
