### ISSUE TITLE
Review FAQ content

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#1593]
Like most FAQs, our FAQ is a big collection of answers that is often added to, but not often returned to by our writers.

The main task of whoever reviews this is to ensure that all content is still accurate + up to date. Sub-tasks would be to improve clarity of answers where they are unclear, move what you see as the most important answers to the top of the file, and/or to create some kind of content organization grouping answers by topic.

**Comment by guimachiavelli** [comment]
FAQs are notoriously disliked by some technical writers. Although I'm not on team "remove all the FAQs"—one of our past surveys indicated that at least some people use it—I still think we should generally strive to move content away from this page whenever possible.

I say that because of two main reasons:
1. I've seen the FAQ sometimes "poisoning" our search results. Meaning, a user searches for e.g. `document id` and the first result is the FAQ instead of our Core concepts > Documents guide;
2. It's harder to keep track of content that's here. I think we do a good job most of the time, but it's always possible core  updates e.g. Error types and we only update the Errors page and not the relevant FAQ question;
3. (bonus reason/I don't know how to count)The FAQ becomes more maintainable because there's less text to review (important since the FAQ naturally requires a lot of context switching).

At a quick glance, I think these sections are prime cutting candidates: 
1. "How can I contact the Meilisearch team" — there are links to github, slack, twitter around the website. If this is a common question, there's something wrong with the design of the docs;
4. "I do not understand the relevancy of my search results." — first of all, not a question (pet peeve). Second, we have a page called Relevancy;
5. "Does Meilisearch deliver an interface to search in my documents"—we already mention the existence the search preview in other pages;
6. "What do the different error types mean"—probably better to mention this in our Errors reference

**Comment by maryamsulemani97** [comment]
Looked up some [best practices](https://larryludwig.com/faq-page-best-practices/), and here are a few things we might want to keep in mind:
1. Can these FAQs be easily addressed in an existing section of our website?
2. Inventing questions for the sake of answering them creates confusion and noise
3. Keep them simple. Make sure the questions are clearly worded and the answers focus on providing a solution, not creating more questions or options.
4. Organize FAQs so users can find answers quickly and easily(if we end up with too many)


Adding to Gui's list:
5. "My document upload failed with the document id is missing error."- this looks like it was copy-pasted from the [document id](https://docs.meilisearch.com/learn/core_concepts/primary_key.html#document-id) section
6. "I am trying to add my documents but I keep receiving a 400 - Bad Request response."- this can go under [Dataset format](https://docs.meilisearch.com/learn/core_concepts/documents.html#dataset-format)
7. "I did a call to an API route and got an object as a response. What does it mean?"- this is mentioned in the quick start and over and over in the API reference
8. "Do I need to configure Meilisearch to get it working?"- the [what is Meilisearch](https://docs.meilisearch.com/learn/what_is_meilisearch/overview.html) section talks about this in a lot of detail
9. "Which languages can Meilisearch handle?"- we have an entire [page](https://docs.meilisearch.com/learn/what_is_meilisearch/language.html) on this
10. "Do you provide a real dataset to test Meilisearch?"- we link the datasets on multiple pages of the getting started. Maybe we could add a link to the [datasets](https://github.com/meilisearch/datasets/) under "More Meili"?
