### ISSUE TITLE
Code doesn't seem to be indexed into the searchbar

### ISSUE THREAD

**Issue by ferdi05** [meilisearch/documentation#1768]
I was looking for `nbHits` in the doc app searchbar, and there was no match..

**Comment by curquiza** [comment]
Maybe @meilisearch/integration-team can help with it, pretty sure this is due to the [scraper behavior](https://github.com/meilisearch/docs-scraper) 😇

**Comment by bidoubiwa** [comment]
It might be because there is no section in the doc that explain the return of a `search` requests. While there is one for the search parameters (see [here for example](https://docs.meilisearch.com/reference/api/search.html#offset))

To be able to find `nbHits` a new section similar to the one I linked should be created.

**Comment by ferdi05** [comment]
Well now we have `estimatedTotalHits` and there's a match, but this may apply to some other content.

**Comment by dichotommy** [comment]
I'm not sure if this behavior is intended, but it seems like the alternative—indexing text from all code blocks and samples—would not be helpful for users. Any Meilisearch-related search term (e.g. `facet`) would return a lot of code sample results and that would make it much harder to find and return an actual guide or similar.

**Comment by ferdi05** [comment]
I see! well I don't have any good idea on how to fix this :(

**Comment by brunoocasali** [comment]
I think this is something expected since we do not have `nbHits` anymore. A way to solve this in my POV is to create multiple documentation per version, like:

- 0.26.x => one index
- 0.27.x => other index
- 0.28x => another index

I think this is something planned after v1, but indeed from what I understood, we could solve the `nbHits` issue by having something like that.

**Comment by guimachiavelli** [comment]
I agree with @dichotommy on this. Indexing the code samples would potentially lower the quality of results. A page can very reasonably include a code sample using an API key and not contain any actual information about security in Meilisearch, for example.

Also, our recent changes to the API reference might have fixed this. We now have lists of all parameters and response fields across all routes, which should account for the majority of terms people would reasonably search for.

**Comment by ferdi05** [comment]
Thanks for the info @guimachiavelli @brunoocasali @dichotommy
Feel free to close the issue when you feel there is no need to discuss this anymore :)
