### ISSUE TITLE
Improve communication about LMDB disk space usage

### ISSUE THREAD

**Issue by oluademola** [meilisearch/documentation#2034]
Hello!

Users have expressed concerns about LMBD disk space usage. There is an understanding this is for optimization, as mentioned in the docs. However, it is not stated when LMDB will start reusing this reserved disk space. Kero mentioned in this [discussion](https://github.com/meilisearch/meilisearch/discussions/3156#discussioncomment-4262368) that LMDB would reuse the space through compaction execution, which occurs each time a snapshot is created. 

It'd be fantastic to mention this in the FAQ or the Snapshot page.

Related issue:

https://github.com/meilisearch/meilisearch/discussions/3156
https://github.com/meilisearch/meilisearch/discussions/3138

Thanks

**Comment by guimachiavelli** [comment]
Thanks for this issue, @oluademola!

Since this is related to LMDB, I think it might make more sense to mention this there.

The part about the snapshots is a bit weird, though. I will follow this up with core, because it sounds bizarre to tell people to generate a snapshot when they actually want to optimize disk usage. As far as I understand the issue, if users need to manually trigger compaction we should give them a proper way of doing it instead of asking them to generate a snapshot because it will coincidentally do the thing they actually want to do.

**Comment by guimachiavelli** [comment]
After talking about this with @Kerollmops, we both agree we shouldn't include the information about the interaction between snapshots and disk space usage. This behaviour is a side-effect, and not an approach we want to encourage. In essence and as far as I understand, users should not have to routinely worry about disk space usage (or engine maintenance tasks like compaction). 

The docs currently emphasise the database will keep growing indefinitely, but are vague when it comes to size limits. I can definitely see how this might make some users a bit uneasy, so after discussing the issue with the @meilisearch/engine-team over Slack (private link), I'm updating the storage guide with more info on the upper boundaries of Meilisearch's disk space usage.
