### ISSUE TITLE
v1.0: versioning documentation

### ISSUE THREAD

**Issue by dichotommy** [meilisearch/documentation#2113]
As Meilisearch transitions into v1, it's necessary to provide users with information about how the core engine, the SDKs, and the documentation will approach versioning.

### Why is this important?

- Understanding **how frequently the core engine will update and which versions will be supported long-term** will help production users choose which Meilisearch version to use.
- Understanding **how SDKs are updated, the relationship between core version numbers and SDK version numbers (if any), and whether or not old SDK versions will be supported** will help SDK users prepare their workflow.
- Understanding **to what extent Meilisearch will maintain documentation for a given version and how to access documentation for previous versions** will help users migrate to newer versions, pick the version they want to use long-term, and set their expectations accurately.

For us at Meilisearch, putting all of this information in a consolidated + visible location should significantly reduce support requests related to these subjects.

### What do we have to do?

- [ ]  Acquire (+ edit) engine versioning policy 
- [ ]  Acquire (+ edit) integration versioning policy
- [ ]  Write [documentation versioning policy](https://github.com/meilisearch/documentation/issues/2070)

### Does this need to be ready for the release of v1.0.0?

**No.** This is a quality-of-life change, and as such there is no hard deadline associated with it. It could be ready alongside v1.0.0 or a few weeks later. However, the sooner we can get the information out there, the better for our support staff and users.

**Comment by dichotommy** [comment]
@curquiza

I see the current engine versioning policy is available [here](https://github.com/meilisearch/engine-team/blob/main/resources/versioning-policy.md). Will this be updated for the release of v1.0? Can we already communicate in this versioning policy about how we plan to approach LTS versions, experimental features, and deprecated features? Even if we change our mind later, I think it could be helpful to provide some information now to get the conversation started with our users.

@brunoocasali 

As we discussed recently, for the documentation we would like a bare minimum versioning policy for the SDKs as soon as possible. This would explain at minimum when new SDK versions are release and why their version numbers do not correspond to Meilisearch engine version numbers. It could also explain whether or not old versions are supported long-term, whether or not documentation for old versions of SDKs is accessible, and anything else that seems helpful for users.

We don't need anything too in-depth for this. Whatever you can provide is great—even bullet points would be better than nothing. Thank you both! 🙏🏻 💪🏻

**Comment by curquiza** [comment]
> @curquiza
> 
> I see the current engine versioning policy is available [here](https://github.com/meilisearch/engine-team/blob/main/resources/versioning-policy.md). Will this be updated for the release of v1.0? Can we already communicate in this versioning policy about how we plan to approach LTS versions, experimental features, and deprecated features? Even if we change our mind later, I think it could be helpful to provide some information now to get the conversation started with our users.

The versioning policy will not be updated, it's already ready for v1.0.0 😊 

About LTS, experimental features and deprecated features, until we don't have any, I don't recommend we talk about them in this file, and in the documentation either. First, because I don't have that much to say about them, but also because the versioning policy file is not related to experimental/deprecated features. Other resources will be created for these. This file is only about how we handle versions. Plus, if it's in the docs, changing anything in these not-stable processes would involve changing the docs as well, which is not comfortable at the moment until the processes are stable.

To give you more concrete information:
- none of experimental/deprecated or LTS processes is required for v1.
- work on [experimental features](https://github.com/meilisearch/meilisearch/issues/3192) has started, but until we don't have any need for experimental features so far, I don't want to communicate officially with the community about what is our process. 
- work on [deprecated features](https://github.com/meilisearch/meilisearch/issues/3193) is really at the beginning, nothing discussed with the team yet
- work on LTS: nothing is planned at the moment. I guess it will be a need of the users in the future, but it's a guess, nothing 100% sure in the coming month/year.

The most important for v1.0.0, from my point of view, is to provide the users with what a version means to us. In the docs it can be a friendlier version [the current versioning policy](https://github.com/meilisearch/engine-team/blob/main/resources/versioning-policy.md), with a redirection to the official one for the most curious ones.

> Understanding how frequently the core engine will update and which versions will be supported long-term will help production users choose which Meilisearch version to use.

Regarding the long-term support, this is not something we have planned so far; we did not get any feedback from the community yet. We will release v1.0.0 first and wait for their feedback about it before starting to do anything. It's important I understand the user needs before promoting any future process. So, we cannot even say "one day we will do it", because I'm not sure yet about what we will do 😢 
However, talking about when we update meilisearch (every 8 weeks...etc) could be a good idea. It's a stable enough process. It does not mean it will not change, but I don't plan to change this every month, so I would accept to change the documentation if there is any change 😊 

Let me know if I miss understood something @dichotommy and thanks for creating this issue ❤️

**Comment by curquiza** [comment]
> which versions will be supported long-term will help production users choose which Meilisearch version to use.

Just thinking about this again, I realize maybe @dichotommy what you mean is to write minimum information like this
- We are following [semver](https://semver.org/) convention and here is the Meilisearch binary [versioning policy](https://github.com/meilisearch/engine-team/blob/main/resources/versioning-policy.md) in details
- We only maintain the latest version of Meilisearch `v1.X.Y`, until we release v2. After releasing a new major release, we will detail here our new maintenance policy with EOL for v1 and later.

Sorry if I spam the issue, I'm not sure to give your the information you need, to I give you all the ones I have 😆

**Comment by dichotommy** [comment]
> Sorry if I spam the issue, I'm not sure to give your the information you need, so I give you all the ones I have 😆

No apology necessary, this is exactly how I like to communicate all the time! 😁 

Thanks so much for your messages @curquiza , they will be very helpful when we start working on this later this week.
