### ISSUE TITLE
Restructure quick start: Installation page

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2125]
As part of restructuring the quick start, we will start with a new dedicated Installation page. This will move the content from the ["Setup and installation"](https://docs.meilisearch.com/learn/getting_started/quick_start.html#setup-and-installation) section of the quick start and the [Supported OS](https://github.com/meilisearch/documentation/pull/2112#pullrequestreview-1261354509) page to the Installation page.
We should also mention the Meilisearch cloud in the quick start and Installation page.

**Comment by dichotommy** [comment]
The new installation page will centralize information related to installation, but some instructions will still need to remain in the quick start so that it can stand alone. The question is, how much?

What is the "bare minimum" so that users can install Meilisearch in a simple and rapid way?

I would say:
- Curl
- Homebrew
- Docker
- Meilisearch Cloud

I feel that eliminating the cloud deploy section and putting everything in tabs is a good idea. WDYT?

I chose not to include AWS, GCP, and DigitalOcean because they are redundant and in some ways in direction competition with Meilisearch Cloud. I think we would prefer users to try the free tier of MC if possible.

On the other hand, that may require users to register an account, whereas they may already have accounts for AWS/GCP/DO. Something to consider!

We could also include APT, if we have space in the tab bar without creating scrolling.

With the "Windows" tab, it's not an installation method in and of itself, so I feel it may make things unnecessarily complicated. I think it makes much more sense to keep the Windows-related information in the installation page. It seems like Windows users will still be able to follow the quick start  using Docker. (But will they know that?)

I also think we may want to get rid of the ASCII `MEILISEARCH`, if only to reduce the amount of vertical scrolling users have to do to get to the meat of the quick start.

Ultimately, we want to reduce the amount of time it takes for users to reach the "A-HA" moment of executing their first search. All changes to the quick start should be done with that in mind.
