### ISSUE TITLE
"Ram Availability" link leads to 404 page on middle-click

### ISSUE THREAD

**Issue by taladar** [meilisearch/documentation#2157]
The link for "RAM availability" in https://docs.meilisearch.com/learn/core_concepts/documents.html#upload works fine on left-click in Firefox and Chrome but leads to a 404 page on middle-click.

**Comment by dichotommy** [comment]
Thanks @taladar , I think it's a caching problem with the redirect 😓 

We will fix this right away, thanks again for reporting it! 🙌🏻

**Comment by guimachiavelli** [comment]
The reported problem is patched for the moment, but we need to investigate the matter further. The current solution is far from ideal.

There's something funny going on with FAQ paths. We'll continue investigating it on #1359, which has a bit more info on the root cause (and also to avoid flooding @taladar's notifications).

Thanks again for the bug report, it's much appreciated ☺️
