### ISSUE TITLE
Migration: Migrate `_redirects` file

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2240]
Migrate the [`_redirects` file](https://github.com/meilisearch/documentation/blob/main/.vuepress/public/_redirects)

**Comment by guimachiavelli** [comment]
Our biggest concern is less migrating the `_redirects` file, and more redirecting the full site. @dichotommy and I were thinking we might benefit from leaving it behind and starting fresh.

For the discussion on the old to new site redirect, consult #2298

**Comment by dichotommy** [comment]
The idea is that rather than migrate our weighty redirects file (which has grown large due to Vuepress generating route based on filepath), we accept breaking some very old links out there on the web.

Due to the overall DNS redirect, they should still travel to the new site meilisearch.com/docs and hit the 404 page, ending up back on the homepage—not the end of the world.

This decision would be mainly for our benefit in terms of maintaining a redirects file. We don't want to carry the full weight of our past mistakes to our work on the new site.

**Comment by guimachiavelli** [comment]
Given time constraints and the reasons outlined by @dichotommy, we'll leave `_redirects` behind without migrating it to nextjs.


Closing this issue as `won't fix`.
