### ISSUE TITLE
Migration: New docs site documentation

### ISSUE THREAD

**Issue by maryamsulemani97** [meilisearch/documentation#2253]
Write content for the new README

**Comment by guimachiavelli** [comment]
@dichotommy, any specific ideas regarding what should be in the readme? Should it simply be an updated version of the one we currently have, or do you have any particular changes in mind?

**Comment by dichotommy** [comment]
I renamed this "new docs site documentation" to focus in on a more specific scope. This issue is now about creating internal documentation so that we and others in the company understand how to manage and contribute to the new docs site.

For outward-facing explanations of the new docs site, see #2280 .

**Comment by guimachiavelli** [comment]
Documentation of the new website, as well as it's current limitations, is located on https://raw.githubusercontent.com/meilisearch/documentation/main/migration-guide.md

We will open new issues to reflect further site improvements, adding missing content, or bringing it up-to-date with post-launch changes.
