### ISSUE TITLE
Add/update cloud touchpoints 

### ISSUE THREAD

**Issue by gmourier** [meilisearch/documentation#2460]
Following meilisearch/mini-dashboard#441 and https://github.com/meilisearch/integration-guides/issues/277, we could update cloud touchpoints for consistency and consider adding where cloud values show the most to raise awareness.

## Homepage and Getting Started touchpoints

Both touch points do not share the same link; I recommend using the same at both places.

- Homepage: `https://www.meilisearch.com/pricing?utm_campaign=oss&utm_source=docs&utm_medium=homepage`

- Getting-started: `https://www.meilisearch.com/pricing?utm_campaign=oss&utm_source=docs&utm_medium=getting-started`

## Considering new touchpoints

We could add touchpoints on the update and deployment guides because the cloud removes this need, so a user might be particularly interested in discovering this information on these pages.

---

Regarding the message, I don't know whether it should be in a marketing tone or more subtle (except maybe for the specifically designed one on the homepage where I would re-use the proposed message in meilisearch/mini-dashboard#441 and meilisearch/integration-guides/issues/277); also it could probably be different and adjusted on every touchpoint in the future.

cc @mayasssh  @davelarkan

**Comment by curquiza** [comment]
By quickly browsing the docs, I also have a lot of ideas to improve the awareness of the Cloud through the documentation.
This issue is definitely a good initiative.

Since focusing on making revenue is the main objective for Q3, I think increasing the awareness of the Cloud through the docs could be a good focus for the @meilisearch/docs-team in the coming quarter. I don't say spending weeks on it, but more like a general and background focus:
- use the creativity of the team and their knowledge of the scope to improve the current docs: @meilisearch/docs-team you will be better than Guillaume and mine to find improvements to do!
- always keep this objective in mind when doing any new tasks to the documentation.

What do you think?

**Comment by guimachiavelli** [comment]
Thank you for creating this issue, @gmourier. I'm not familiar with the term touchpoint here, but from the context I infer you mean links in the docs pointing to Meilisearch Cloud-related pages.

Reviewing and adding more links to Cloud-related resources is in our plans. As @curquiza said, there are certainly a few places where we can raise Meilisearch Cloud awareness. We will start dedicating resources to this task shortly after v1.3 updates are ready.

Regarding tone: I'll be exaggeratedly blunt. We should never use a persuasive/marketing-oriented tone in the docs. Using a persuasive tone will erode user trust and actively diminish the value of the docs. The documentation can, should, and will raise awareness, but it can't sell.

I agree the docs are a valuable venue for raising Cloud awareness (and, consequently, company profits). However, this value is directly tied to us being perceived as a reliable source of information. The moment users feel we're trying to sell something to them instead of informing them, they will (rightfully) question our reliability. Think of it like a newspaper: if your favourite news website started publishing articles about how great a specific product is, you would start to question how much you can trust them. You would question it even more if it's clear the news website will profit from this product's sales.

**Comment by guimachiavelli** [comment]
We have organically added quite a few links since the creation of this issue. Based on a review of the current website plus suggestions from other team members, these are a few other low-hanging fruits where we can add more links without having to significantly alter the surrounding content:

- [ ] `/learn/getting_started/getting_ready_for_production.mdx`
- [ ] `/learn/cookbooks/running_production.mdx`
- [ ] `/learn/what_is_meilisearch/overview.mdx`
- [ ] `/learn/getting_started/search_preview.mdx`
- [ ] `/learn/security/master_api_keys.mdx`
- [ ] `/learn/experimental/vector_search.mdx`
