### ISSUE TITLE
How-to guide on document pinning

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2517]
@meilisearch/product-team and @meilisearch/devrel-team are currently working on communicating workarounds to cover functionality Meilisearch does not yet offer. One of these is document pinning: in short, ensuring a document is always the top search result.

The @meilisearch/devrel-team has written a blog teaching users how to pin documents with React and InstantSearch. They have requested to feature this content on the docs since the documentation has higher visibility than the blog. 

As previously stated, the docs currently avoids publishing guides and tutorials with third-party dependencies. At the same time, @Strift is correct in saying docs users who search for document pinning will not find anything at the moment.

Based on our discussion so far, I see three ways of doing this:

1. Publishing the blog post under "Cookbooks" with minor editorial changes bringing it inline with the rest of the docs;
2. Finding a spot in the docs where we can explicitly mention "document pinning" and link this mention to the blog post;
3. Reworking the blog post in a dependency-agnostic version using e.g. vanilla javascript (similar to what we do for [search result pagination](https://www.meilisearch.com/docs/learn/front_end/pagination)).

My personal preference is #3, since this might make the resource uniformly useful to all front-end devs, instead of only those who use React. On the other hand, depending on implementation complexity a vanilla JS how-to guide might end up being counter-productive. Do we have any data regarding front-end frameworks preferred by our users?

**Comment by Strift** [comment]
Hi @guimachiavelli, thanks for creating the issue 🙏 

I'm in favor of **Option 2** because it requires minimal new writing and synchronization between docs, devrel, or product.

I'm thinking of including minimal content on the page / section:

- Explain that Meili is currently working on the feature (link to product board)
- Explain that while the feature is WIP, we offer workarounds
- Link to the React workaround guide and future other guides we might write

There are "look and feel" disadvantages to this approach, but I think it's the quickest to implement. It's also simpler to roll out as it requires less sync between teams.

**About framework usage**

We don't have numbers of downloads to use as all our JS implementations use the same library. That being said, React is without a doubt the most used frontend framework (at least in the West.)

What we have, however, is Github repositories traffic metrics. Over the last 2 weeks `meilisearch-react` got 2x more visitors than the Vue counterpart, and 3x more than the Angular one. 

For the record, it got almost as much traffic (80%) as the `meilisearch/instant-meilisearch` repo (which is needed regardless of whether you're using Vanilla JS, or a JS framework.) 

It's a bit of a stretch but I don't think it's misleading to think most of our users use React.

**Comment by guimachiavelli** [comment]
Ok, that works for me. Do you have any preferences as to where you'd like that bit of content? Perhaps "Indexes" or "Relevancy"?

**Comment by Strift** [comment]
Awesome!

"Relevancy" sounds better to me, as this is probably where I assume we would have it if the feature existed.

**Comment by Strift** [comment]
Update — we now have published a second guide to provide an alternative workaround for this feature: https://blog.meilisearch.com/document-boosting/

Both should be included IMO :)
