### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#2546]
Hello! 

Running the scrapper on the documentation, it raised two broken links that are used in the documentation: 

- https://www.meilisearch.com/docs/learn/experimental/learn/configuration/instance_options
- https://www.meilisearch.com/docs/learn/advanced/reference/api/facet_search

**Comment by guimachiavelli** [comment]
Thanks for creating the issue!

I cannot find these with grep and the like. Looking at the links and how they sort of nest sections that have never been nested (e.g. `reference/api` as a sub dir of `learn/advanced`), I'm thinking these might be due to a missing / at the beginning of a link. For example, a link to `learn/configuration/instance_options` instead of `/learn/configuration/instance_options`.

**Comment by guimachiavelli** [comment]
Fixed by #2545
