### ISSUE TITLE
apt key should be added

### ISSUE THREAD

**Issue by WilliamDEdwards** [meilisearch/documentation#2620]
The documentation tells users to use the apt repository `deb [trusted=yes] https://apt.fury.io/meilisearch/ /`.

However, usually, users are instructed to add a key with which packages are released. The `[trusted=yes]` statement in the line above prevents that.

From a security standpoint, this is a huge no-no.

I have opted to create this issue in the documentation repository, as I cannot imagine that 'fury.io' does not have a key, but rather it is simply missing from the documentation.

**Comment by Axodouble** [comment]
This would indeed be a lovely feature, the security vulnerabilities that this may pose are certainly something worth avoiding.

I looked for it prior as well and couldn't find it.

**Comment by guimachiavelli** [comment]
Thanks for creating this issue, @WilliamDEdwards. 

The person managing our package pipeline (and, thus, who can properly assess the best solution here) is on holiday at the moment, but we will pick this up as soon as they're back.

**Comment by curquiza** [comment]
Hello @WilliamDEdwards 

Let me know if https://github.com/meilisearch/meilisearch/issues/1275 is what you are talking about.

It has not been prioritized yet since we are a small team and we had to prioritize other things, sorry for this. Plus, the massive usage of Meilisearch is done via Docker, not via APT.

However, if you can give some clues about what should be done in the issue I linked, it will help our team do it faster

I close this issue since it's not about documentation.

**Comment by WilliamDEdwards** [comment]
> Let me know if [meilisearch/meilisearch#1275](https://github.com/meilisearch/meilisearch/issues/1275) is what you are talking about.

Correct. This issue did not show up in my earlier searches.

> However, if you can give some clues about what should be done in the issue I linked, it will help our team do it faster

I'm not sure this can be made more specific than that issue already is.
