### ISSUE TITLE
v1.6: Proximity setting

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2653]
v1.6 introduces a new index setting, `proximityPrecision`. It accepts one of two string values: `wordScale` and `attributeScale`. `wordScale` is the default and presents no significant change from previous Meilisearch releases. `attributeScale` makes calculations simpler and faster, but less precise: instead of counting the distance between terms, Meilisearch only checks whether search terms are present on the same attribute. Disabling this ranking rule might impact relevancy.

## Tasks
- [x] Update `/reference/api/settings.mdx`
- [x] Update `/learn/core_concepts/relevancy.mdx`

## References
- Usage: https://www.notion.so/meilisearch/Customize-proximity-precision-usage-aa69c2bab2c3402bab9340ae4def4577
- engine issue: https://github.com/meilisearch/meilisearch/issues/4187
- SME: @ManyTheFish

**Comment by ManyTheFish** [comment]
Hello @guimachiavelli,
For now, the variants are `attributeScale` and `wordScale`, but I will change them to `byAttribute` and `byWord` because of the ambiguity of the suffix `Scale`, and its redundancy with the suffix `Precision` of the setting name.

> attributeScale effectively disables the proximity ranking rule

not really. It reduces the precision of the proximity-based features like the proximity ranking rule or the phrase search, but they are not deactivated. The real effect is a trade-off that can be summaries as:
"""
do you prefer:
1) A higher precision when computing the distance between the matching query words (how many words separate the matching words?), but a higher indexing time
2) Or a lower precision when computing the distance between the matching query words (Are the matching words in the same attributes?), but a lower indexing time

"""

**Comment by guimachiavelli** [comment]
Hi @ManyTheFish—thanks for clarifying this, it's a lot clearer to me now. I'll fix the issue description.
