### ISSUE TITLE
Improve Webhook URL docs

### ISSUE THREAD

**Issue by curquiza** [meilisearch/documentation#2683]
Following this feedback: https://github.com/meilisearch/meilisearch/discussions/4331#discussion-6081985

@tacman you can continue the discussion with our docs maintainer (@guimachiavelli) here if needed

**Comment by tacman** [comment]
How about just any working example in any language?  This seems like a really great feature, but because of the lack of documentation and example, it feels like it's an internal feature that is sort of a hidden gem that happens to be exposed.

I have an idea on how to use this to update a monitoring script use SSE (https://minompi.medium.com/server-sent-events-with-php-and-symfony-5d6596cc84c8).  Obviously, it's easy to keep polling the server with ->stats() and the like, but listening for the task completion event and pushing them to clients would be pretty cool.

**Comment by guimachiavelli** [comment]
Hello @tacman!

Thanks for bringing this up. We originally developed the webhook for internal use and were unsure whether it would be useful outside our specific case. Since release time is a bit hectic and we have limited resources, we decided to keep documentation of this feature very light, and improve it in case we saw users were interested in it.

I plan to add a short guide with a few code samples outlining how to use the "task completed" webhook in the coming week. I'll update this issue once it's online.

Meanwhile, and in case you didn't see it already, this is the webhook information currently available in the docs: https://www.meilisearch.com/docs/learn/configuration/instance_options#task-webhook-url and https://www.meilisearch.com/docs/learn/configuration/instance_options#task-webhook-authorization-header

**Comment by tacman** [comment]
Yes, I see.  It's returned in this format: https://ndjson.org/

![image](https://github.com/meilisearch/documentation/assets/619585/e72b7af0-a83b-45e7-be04-9745592ee20a)

PLEASE add some documentation that includes the returned data example (POST?  Content Body?)  

I haven't even been able to get it to call the task url.  It's definitely a worthwhile feature, I can't wait to get rid of polling stats() until isIndexing == false.
