### ISSUE TITLE
Timestamp fields on update

### ISSUE THREAD

**Issue by virik** [meilisearch/documentation#2692]
Hi,

I tried to find information about this in the documentation, but I couldn't find any. Let's say I have a "created" field and a "updated" field. The created field should never change, as it is the date the record was added to the index. How to leave this field intact on update. Maybe you could add some information about this to the docs?

**Comment by guimachiavelli** [comment]
Hello @virik—thanks for getting in touch!

From your description, I assume you are using the `POST` endpoint of the `/indexes/{index_uid}/documents` route. `POST` is useful for adding and completely replacing documents. 

When you want to partially update a document—for example, if you only want to set your `updated` field to a new timestamp value—[use the `PUT` endpoint](https://www.meilisearch.com/docs/reference/api/documents#add-or-update-documents).

Let me know if this helps!

Also, for future reference: we're happy to get user feedback here, but if you are on a rush you can also reach out to our support staff on the [Meilisearch Discord server](https://discord.meilisearch.com/). They tend to reply much more quickly than the documentation team.

Thanks again!

**Comment by virik** [comment]
hi,

No, I'm using the PUT endpoint. Let's say we have 1 existing product and 1 new product, and a timestamp called "created". For the new product we need to set the timestamp, but for the existing product we should not change it. There should be a way to specify which fields to ignore on existing records.

**Comment by guimachiavelli** [comment]
Ah, apologies for the misunderstanding. I believe the only solution would be to make two requests: one `POST` request adding new products, and one `PUT` request updating existing products. As it stands, and if I understand your use case correctly now, I don't believe this is a documentation issue: there is no Meilisearch feature that does exactly what you need it to do.

If you [get in touch with our support team on discord](https://discord.meilisearch.com/), they might be able to help you come up with better workarounds.

Closing this issue since the docs repo is not the best place for providing user support.
