### ISSUE TITLE
v1.9: Relevancy changes

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#2852]
v1.9 no longer takes attribute order in consideration when ranking documents in indexes using the default value for `searchableAttributes`, `[*]`.

Behaviour remains the same when `searchableAttributes` has been configured, however. If `searchableAttributes: ["title", "description"]`, matches in `title` will be more important than matches in `description`.

## Tasks
- [ ] Update https://www.meilisearch.com/docs/learn/core_concepts/relevancy#attribute-ranking-order (remove most of the section

## References
- engine issue: https://github.com/meilisearch/meilisearch/issues/4639
- SME: @irevoire

**Comment by irevoire** [comment]
> v1.9 no longer takes attribute order in consideration when ranking documents in indexes using the default value for searchableAttributes, [*].

FIY, that’s not exactly what was happening before.
Before v1.9, we were using the first order of apparition of the fields, which means that if you sent:
```json
[
  {
    "id": "the human tamo",
    "favorite beverage": "kefir"
  },
  {
    "favorite beverage": "milk",
    "id": "the doggo kefir"
  }
]
```

The internal searchable attributes generated would have been `["id", "favorite beverage"]` even though the second document used a different order. (They'll also be returned in the ordering found by the engine in case of a search request.)
And now, regarding relevancy changes, if I were searching for `kefir` before v1.9, I would get the second document first as it contains the word kefir in its « first » field (from the pov of the engine).
While, after v1.9, the first document will be returned first.
Since all fields share the same importance, the only thing that matters here is how close `kefir` is from the beginning of the field.

---

I'm not sure it'll really help you to write the documentation, but I just wanted to clarify why the previous behavior didn't make much sense and was only implemented this way for technical reasons.
