### ISSUE TITLE
How to keep keys when restarting Meilisearch 

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/documentation#2905]
I've seen recently some user wondering about deterministic API keys, they want to know how to keep the same keys when restarting an instance.

> I'm using Meilisearch in Render and every month they update the server manually and so the API keys are updated, which causes problems in my applications because I have to update the API keys.
> 
> Is there any way to keep the API keys fixed even if the server restarts? Can I generate the API keys and pass them on via an environment variable?

Also they seem confused about which keys are deterministic:

> I'm running meilisearch with the same master key (and backed by the same EBS volume) and I'm sometimes getting different 
> admin API keys
> 
> I was under the impression keys were deterministically based on the master key, and would only change when the master key changes?
> Is this assumption invalid or is this a bug (either in my code or Meilisearch)?

**Comment by guimachiavelli** [comment]
Ok, took me some time, but finally made the time to dig a bit into this.

In short:

1. API keys are, roughly speaking, a hash from the master key and an UUID
2. If two instances share the same master key (e.g. `carolina123`), generating an API key with uuid `0000000-0000-0000-0000-00000000000`  will result in exactly the same API key in both instances
3. Since you cannot specify their uuids, users should not use the default API keys when they need their API keys to be deterministic

In the case of this user, they would have to stop using the default autogenerated API keys and add an extra step to their restart workflow where they create the keys they need by specifying their uuid.

**Comment by CaroFG** [comment]
Thank you! Yes, that's what I told him. I created the issue as a content piece or improvement suggestion. It seems some users expect to get the same default API keys if they run an instance with the same master key, which is not the case.
