### ISSUE TITLE
Adding GitHub search to Meili docs

### ISSUE THREAD

**Issue by erlend-sh** [meilisearch/documentation#339]
In similar fashion to this [multi-site search](https://github.com/meilisearch/MeiliSearch/discussions/628), docs.meilisearch.com could include GitHub Issues (and eventually Discussions) as an additional search source:

<img width="823" alt="Screenshot 2020-04-23 at 10 11 27" src="https://user-images.githubusercontent.com/583842/80076592-b8a43780-854c-11ea-9ae7-8db20506bd30.png">

_Originally posted by @erlend-sh in https://github.com/meilisearch/MeiliSearch/discussions/629_

**Comment by tpayet** [comment]
In order to achieve GitHub search to Meili docs we need 2 things:
- GitHub issues and pull request indexer
- modify [docs-searchbar.js](https://github.com/meilisearch/docs-searchbar.js) in order to display multi-index result.

The first one can be implemented asap but I would like some feedback from @curquiza & @qdequele on how to modify docs-searchbar. How complicated would that be?

**Comment by curquiza** [comment]
About `docs-searchbar.js`, it's doable, but it would be waaay easier if MeiliSearch would handle the multi-indexes search instead of adapting our tools...

The search in the library is done [here](https://github.com/meilisearch/docs-searchbar.js/blob/12adc7afda5a730c67babfd92e6ec63e28db9862/src/lib/DocsSearchBar.js#L224-L241). 

In any case, we have to change [the `indexUid` field](https://github.com/meilisearch/docs-searchbar.js/blob/12adc7afda5a730c67babfd92e6ec63e28db9862/src/lib/DocsSearchBar.js#L13): it could be an array or a string (currently just a string is allowed) and we could adapt the search depending of this type. With this solution, the new version would be non-breakable.

**Comment by Kerollmops** [comment]
Hum, ok yeah.

The multi-indexes search doesn't mixup the results of the different indexes you are searching in, it only returns an array with the different results you would have found if you had requested each indexes independently. The engine can't fix them up because the schema is different and therefore it don't know which fields are better than another.

Your new serach bar setup seems good, but are you sure you can fit the Github documents into the documentations index? Is the schema equivalent? Will it work?

**Comment by curquiza** [comment]
> The multi-indexes search doesn't mixup the results of the different indexes you are searching in, it only returns an array with the different results you would have found if you had requested each indexes independently. The engine can't fix them up because the schema is different and therefore it don't know which fields are better than another.

Ok so with my suggestion I indeed don't need the multi-indexes search.

> Your new serach bar setup seems good, but are you sure you can fit the Github documents into the documentations index? Is the schema equivalent? Will it work?

That might be complicated but possible. I need to test that and let you know 🙂 I think that could work. The question is more about the apparition priority of the GitHub results in the search bar. I need to find the right settings for that.

**Comment by curquiza** [comment]
Here is [an issue](https://github.com/meilisearch/docs-searchbar.js/issues/40) I've just opened for a user. It's exactly our kind of use-case.
The answer I wrote down clarifies a lot about what to do.

Here is the hierarchy we thought with @tpayet:
- `lvl0` -> `GitHub`
- `lvl1` -> `Issue` or `Pull Request`
- `lv2` -> title of the issue/PR
- `content` -> the comments of the issue/PR

**Comment by guimachiavelli** [comment]
We have discussed this internally and are against adding search issues to the main searchbar. We are afraid it will create too much noise—searching for something and ending up on an ongoing discussion about something that has not been solved might be frustrating and confusing, especially for more inexperienced users. Users come to the docs for unambiguous answers and usage instructions, something which issues only occasionally supply.

@dichotommy does believe having a separate search bar might be useful for users who have been unable to find the answer to a problem.
