### ISSUE TITLE
It's better to compile for performance

### ISSUE THREAD

**Issue by tpayet** [meilisearch/documentation#346]
We should write somewhere in the documentation:
https://github.com/meilisearch/documentation/pull/343#issuecomment-623486362

**Comment by Kerollmops** [comment]
We must talk about that and specifically the env variable `RUSTFLAGS='-C target-cpu=native'`.

**Comment by bidoubiwa** [comment]
Can this PR be closed? @tpayet

**Comment by eskombro** [comment]
This is an interesting discussion!

I have always wondered what the impact of compiling natively instead of retrieving a remote binary could be! :)

But never got/took the time for a research on that matter...

If someone has any info about it (even just a little simple 2 lines explanation as a starting point) it would be great to learn about it!

**Comment by Kerollmops** [comment]
This is better to compile with some specific flags (i.e. `--target-cpu=native`), by doing that you will specialize your program for the cpu your compiling on, it means that some instruction that your cpu support can be used instead of using other less performant but more portable.

See "Instruction sets are architecture-specific" on [the SIMD wikipedia page](https://en.wikipedia.org/wiki/SIMD#Disadvantages).
