### ISSUE TITLE
Move DigitalOcean Marketplace docs

### ISSUE THREAD

**Issue by erlend-sh** [meilisearch/documentation#358]
There are two docs on https://github.com/meilisearch/meilisearch-digital-ocean that probably ought to get a new, permanent home on docs.meilisearch.com:

(PR pending with an updated screenshot referring to the proper Marketplace instead of custom snapshots)
https://github.com/meilisearch/meilisearch-digital-ocean/blob/master/scripts/README.md

https://github.com/meilisearch/meilisearch-digital-ocean/blob/master/server/README.md

The current Getting Started docs assume local-only installation. We might need a slight restructuring here to fit in the "Launch on DigitalOcean" option.

There's also an example of an official DO button plus a link with our referral code [here](https://github.com/meilisearch/MeiliSearch/pull/675).

**Comment by eskombro** [comment]
We were exploring different paths on the DigitalOcean marketplace, and that's why things got a little bit confusing! I'll go back to the previous idea of having in the base of the repo a readme on how to use MeiliSearch on the marketplace, user-oriented, and update the guides, as they were done while the official MeiliSearch image wasn't actually published in the marketplace! Thanks @erlend-sh

**Comment by eskombro** [comment]
About having that in the official documentation, I am not sure... would like to get some feedback from @bidoubiwa @tpayet @curquiza

**Comment by curquiza** [comment]
I'm not sure the users would know there is MeiliSearch image on the market place, because most of them will not go to this repo. They read the docs and sometimes, the MeiliSaerch README (I saw the @erlend-sh [PR about that](https://github.com/meilisearch/MeiliSearch/pull/675)).

So, I would rather have a small page about that, so that when you type "digital ocean", or "marketplace" in the search bar, you can find it 🙂

**Comment by bidoubiwa** [comment]
resolved by @eskombro: meilisearch/documentation#362
