### ISSUE TITLE
Improve the documentation related to the schema-less feature

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/documentation#375]
A user on our community Slack reported that the schema-less feature explanation was a little bit confusing, could we improve some of these sentences? :)

https://meilicommunity.slack.com/archives/CP9DVS1RQ/p1590160052376000

**Comment by react-learner** [comment]
I am closing this issue, because all fields are now searchable and displayed by default (consistent with schema-less design). 

Additionally, with the new changes to the searchable attributes docs (#652 ), it should be clear to anyone manually changing the searchable attributes list that doing so will require future attributes to also be added manually.
