### ISSUE TITLE
Docs examples: error on Add or update documents examples

### ISSUE THREAD

**Issue by eskombro** [meilisearch/documentation#405]
While checking the [Add or update documents examples](https://docs.meilisearch.com/references/documents.html#add-or-update-documents) I see both examples (`curl` and `js`) try to update a document with a field called `movieskud` that doesn't exist in the other documents and examples. I think this is an error and should be changed for `id`

**Comment by curquiza** [comment]
If I'm not wrong, that's the point: showing that we can add a new field 😉

**Comment by eskombro** [comment]
This might be true, but in that case we are using a data-set example where there is a field called `id` (in the same page, and all over the docs). This means that the [Add or update documents example](https://docs.meilisearch.com/references/documents.html#add-or-update-documents) would be missing the `primary key` and the update would fail. I still think this example isn't appropriate :)

**Comment by curquiza** [comment]
Ah, I thought you only wanted to replace the `movieskud` by `id`. The primary key is indeed missing, but I don't think we should remove the `skuid` field because the `skuid` is used a lot by eCommerce website!

(Btw, it should be `skuid` and not `skud`, right @bidoubiwa?)

**Comment by bidoubiwa** [comment]
The purpose of this example is to showcase that you can add a primary key when using that route.
This example suppose you do not have an `id` field but a field that does not have the word `id` in it. Since it would have been inferred otherwise. This example imagines a scenario where a user fall into the category of a non-inferrable primary key, fails to upload his documents, comes to the documentation, stumble upon this example, and observe how he can communicate his specific primary key by using: 
` -d 'primaryKey=movieskud'` 

```
$ curl \
  -X POST 'http://localhost:7700/indexes/movies/documents' \
  -d 'primaryKey=movieskud'
  --data '[{
      "movieskud": 287947,
      "title": "Shazam ⚡️"
  }]'
```

I agree with you on the fact that this query parameter should not exist because it is confusing (see 
meilisearch/MeiliSearch#738). So maybe this example should be avoided. 

Nevertheless, examples that go against the dataset are a reality in the documentation. Sometimes this dataset does not go well with what we want to showcase (i.e the facets). 
The reference examples are not bounded with the movie dataset, it is also mentioned nowhere that all the examples are compatible with the movie dataset.

**Comment by curquiza** [comment]
Ok I did not notice the `-d 'primaryKey=movieskud'`

2 points:
- the JS does not mention the `primaryKey`
- an introduction sentence could be great to explain that no primary key was set before (and that's the first time we are adding documents). Because, if I'm not wrong, we cannot change the `primaryKey`.

**Comment by curquiza** [comment]
For those coming there: the final decision was to remove the primaryKey in this example because too confusing.
