### ISSUE TITLE
"Setting Up Facets" section - clarification about "at indexing time"

### ISSUE THREAD

**Issue by rsalmond** [meilisearch/documentation#446]
[This section](https://docs.meilisearch.com/guides/advanced_guides/faceted_search.html#setting-up-facets) includes the important caveat: "Attributes that could be used as facets must be declared at indexing time.". After playing with this feature it appears what this means is that "Attributes that could be used as facets must be declared **prior to** indexing".

In my testing I found that the `settings/attributes-for-faceting` endpoint would accept field names for already-indexed documents and return a 202, and then return an empty list when you turn around and GET to make sure your attributes are there. I could only confirm my facet attributes had been accepted after deleting my test docs, POST'ing the attributes, and then re-indexing the documents.

If my assessment is correct, I suggest that the "before indexing" distinction is clearer than "at indexing time" and will help avoid confusion. Also, if getting back an empty list of attributes is expected behaviour when facet attributes have been added but no new documents have been indexed yet, that's worth calling out in the docs as well. Getting a 2xx code at creation followed by an empty set of attributes at verification is counter-intuitive to common REST mechanics.

**Comment by bidoubiwa** [comment]
Hey, 

You are absolutely right. This part is confusing. Your assumptions are not correct which made me realise it is really not clear. 
I'm making a pull request to improve this part.

For an attribute to be used as a facet, it **has to be previously added to the settings**. In the settings, the chosen attributes must be added to the `attributesForFaceting` list.
This step is required because facet needs to be properly processed and prepared by the engine in order to be usable.
