### ISSUE TITLE
Wrong index name in example

### ISSUE THREAD

**Issue by Mubelotix** [meilisearch/documentation#471]
The cURL example for the `Update Index` route at https://docs.meilisearch.com/references/indexes.html#example-4 is using the index `movie_review` but the Javascript and Python examples are using `movies`.

**Comment by Mubelotix** [comment]
Something similar at https://docs.meilisearch.com/guides/advanced_guides/search_parameters.html#filters . The query of the second example differs between cURL and other languages.

**Comment by Mubelotix** [comment]
Same issue in the example of https://docs.meilisearch.com/guides/advanced_guides/settings.html#distinct-attribute. Javascript and python are using the `movies` index instead of `jackets`?

**Comment by Mubelotix** [comment]
Same issue [here](https://docs.meilisearch.com/guides/advanced_guides/distinct.html) but only Python is wrong.

**Comment by guimachiavelli** [comment]
## Remaining code samples to update
- [ ] `update_an_index_1`: update JS, Python, PHP, Ruby and Go samples must use `movie_reviews` 
- [ ] `settings_guide_distinct_1`: JS and Python samples must use `jackets`

## Summary

### Update index route (references/api/indexes#update-an-index)
Inconsistency still exists: Rust and cURL refer to the `movie_reviews` index, other examples refer to `movies`. 

Solution: update  examples so they all use `movie_reviews` since a previous example in the same page mentions the existence of a `movie_reviews` index.

### Filters search parameter (reference/features/search_parameters#filter)
This search parameter has been deprecated in v0.21. The reported issue is no longer relevant.

### Distinct attribute setting (reference/features/settings#distinct-attribute)
Inconsistency still exists. JS and Python samples still point to a `movies` index that is irrelevant for the example at hand.

Solution: update both JS and Python samples so they point to `jackets`.

### Distinct attribute feature (reference/features/distinct#example)
This has been fixed in a previous PR.

**Comment by dichotommy** [comment]
@guimachiavelli When you have a free moment, could you take a look at the status of this issue?

**Comment by maryamsulemani97** [comment]
Update:
1. `update_an_index_1` should use the `movies` index for the **curl, Java and Go** code samples
2. `settings_guide_distinct_1` should use the `jackets` index for the **JS** code sample
3. `distinct_attribute_guide_1` should use the `jackets` index for the **Swift** code sample

**Comment by dichotommy** [comment]
Fixed by:

1. Curl: https://github.com/meilisearch/documentation/pull/1422, Java: https://github.com/meilisearch/meilisearch-java/pull/337, Go: https://github.com/meilisearch/meilisearch-go/pull/267
2. JS: https://github.com/meilisearch/meilisearch-js/pull/1150
3. Swift: https://github.com/meilisearch/meilisearch-swift/pull/253
