### ISSUE TITLE
How does lazy index impact the documentation

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/documentation#583]
With the arrival of lazy index meilisearch/MeiliSearch#918 we have to consider how it will impact the documentation. 

Should indexes be put to the background since their knowledge is not essential to working with MeiliSearch?

This can be done through different changes: 

- Remove explicit index creation from getting started #571 
- Talk about index creation in the indexes guide the way mongo db does with databases and collections: https://docs.mongodb.com/manual/core/databases-and-collections/
- Remove the index guide from the main concept, or add it after `relevancy` instead of as the first guide.
- Move the [API references of indexes](https://docs.meilisearch.com/references/indexes.html) lower in the list. Maybe after update?

**Comment by react-learner** [comment]
I think this change is intended to simplify things for lower-level users by hiding indexes "under the hood", but in my opinion there is only so far we can go in this direction, since even adding or accessing documents requires an index ID and many important settings are also tied to indexes.

Here is what I think of the proposed changes: 

- In getting started, explicit index creation should be briefly mentioned, maybe in a single sentence, but not demonstrated.
- In the main concept guide, we should definitely add an implicit vs. explicit comparison section similar to MongoDB's. Implicit: default option, simple, less code. Explicit: more error-proof.
- In terms of the sidebar order, I think Documents and Indexes should just be switched both in Main Concepts and API References.

**Comment by react-learner** [comment]
Closing this because all suggestions (sidebar order aside) have either been implemented, or created as separate issues.

**Comment by bidoubiwa** [comment]
In [`indexes` core concept](https://docs.meilisearch.com/learn/core_concepts/indexes.html#index-creation) it could be an idea to talk about the implicit index creation. Apparently not only `POST /documents` creates the index in the background. 

In the [index creation](https://docs.meilisearch.com/learn/core_concepts/indexes.html#index-creation) part we can talk about it.
