### ISSUE TITLE
Add information about MeiliSearch behavior on Windows

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/documentation#660]
There's very little information about MeiliSearch support and use on Windows.

**Comment by react-learner** [comment]
I believe we want to avoid creating a separate guide or even sub-section for Windows installation, because this would give the impression that we support/encourage running MeiliSearch on Windows (we don't, as far as I know). Given this, I think we should add a lengthy "warning" (::: warning :::) in guides/advanced_guides/installation.md where we state the following:

- Windows installation should be performed either through Docker or by compiling from source
- A common compilation error ("link.exe not found") can be solved by installing Build Tools for Visual Studio
- MeiliSearch will allocate 100gb on launch. If memory is an issue on your machine, modify max MDB and UDB size accordingly (link to guides/advanced_guides/configuration.md#max-mdb-size).

Is there anything that I'm forgetting?

**Comment by react-learner** [comment]
One other file should probably be changed: /resources/about_storage.md. There, we can give a more thorough and technical explanation of why MeiliSearch allocates 100gb on Windows.

**Comment by CaroFG** [comment]
Maybe a mention in the FAQ too?

**Comment by bidoubiwa** [comment]
There was once a suggestion to improve the installation guide by adding every common OS: windows, mac and Linux instead of specific tools like apt-get and brew. 
I don't know if it is something we want. But it seems to be the way other common tools make their installation guide.
For example in cockroachDB: https://www.cockroachlabs.com/docs/stable/install-cockroachdb-mac.html

**Comment by CaroFG** [comment]
Apparently, we should not encourage people to use MeiliSearch on Windows through a dedicated section or a tutorial...

**Comment by bidoubiwa** [comment]
We could add a warning that it is a bad idea to run production (or even just meilisearch) on windows, and insist that they use docker or another tool. I think it is important to make it really simple for users to quickly test MeiliSearch, whichever env they are on. After which, if they want to use it in production, they might follow best practices. Also, most of the time when using MeiliSearch in production it is on a hosted Linux server. I'm not sure there are a lot of hosted windows out there but I might be wrong! 

But this decision is not mine to make so don't worry! If you feel it is not a good idea or it is too soon to consider a multi OS installation guide, feel free to postpone it. 
Also, side note, we could still change the guide by adding Linux and Mac OS and not windows.

**Comment by fharper** [comment]
We should definitely have a full installation process for macOS & Linux, but as discussed last week, let's not do something with too many details for Windows. The minimum with a warning that we don't encourage using Windows because of how memory is managed. It may change with the new engine, though.
