### ISSUE TITLE
Add information about update guaranties  

### ISSUE THREAD

**Issue by pythoneer** [meilisearch/documentation#661]
I have searched about specific information about the guaranties the `update` endpoint makes. From the corresponding slack discussion: 

When i am doing a "batch" update with multiple documents at a time does meili do it in an atomic way, such that either no update in any document is visible or all updates from that particular invocation is visible in all documents? e.g. i am updating 3 documents with a single update invocation is it possible for a query/get documents invocation to see only the update of 1 or 2 documents but an "old" third document?

**Comment by fharper** [comment]
Thanks @pythoneer !

**Comment by react-learner** [comment]
Hm, good question @pythoneer . I know that the document addition request in MeiliSearch is atomic (mentioned [here](https://docs.meilisearch.com/guides/main_concepts/documents.html#primary-field) of all places), but I'm not 100% sure that the same is true of the update endpoint. Will ask the developers and get back to you.

Either way, it should definitely be noted in the documentation.

**Comment by react-learner** [comment]
@pythoneer I have confirmation from the developers that all of MeiliSearch's asynchronous processes are atomic. You can read more [here](https://docs.meilisearch.com/guides/advanced_guides/asynchronous_updates.html#killing-meilisearch-while-a-task-is-processing).

(The only exception is [implicit index creation](https://docs.meilisearch.com/guides/main_concepts/indexes.html#index-creation); since this is actually two processes—create an index, then add documents to it—it's possible for only "half" the operation to be executed—an index is created, but no documents added—if the latter process fails or is terminated.)
