### ISSUE TITLE
Recommended requirements for hosting

### ISSUE THREAD

**Issue by tobyglei** [meilisearch/documentation#721]
**Is your feature request related to a problem? Please describe.**
Recommended requirements for hosting

**Describe the solution you'd like**
Would like to see some documentation similar to this on MeiliSearch:
[https://strapi.io/documentation/developer-docs/latest/getting-started/deployment.html#recommended-requirements](https://strapi.io/documentation/developer-docs/latest/getting-started/deployment.html#recommended-requirements).

More specially, I'm looking for number of CPU cores and memory to host MeiliSearch in a production server.

**Comment by react-learner** [comment]
Thanks @tobyglei  for creating this issue. Will check with the developers and update the docs ASAP.

**Comment by tobyglei** [comment]
Still waiting for an update on this. Thanks guys

**Comment by react-learner** [comment]
Hey @tobyglei , sorry for the delay in getting back to you. Truthfully this is not an easy question; disk size and RAM usage of the database depend on a large number of factors, including which relevancy rules you use, the languages in your dataset, the number of repeated words, whether or not you use faceting, the list goes on.

In the future we plan to provide thorough benchmarking with lots of different datasets, but that takes time, and isn't a priority for this engine since **we have an entirely new engine coming** that will change everything. In any case, here are a few general principles:

- Because MeiliSearch uses a memory map, the search speed is based on the ratio between RAM and database size. If you have very little RAM and a large database, search can become quite slow. On the other hand if you had equal RAM and database size, search would be almost instantaneous.
- The number of CPU cores has a high impact on indexing speed—not much impact on search.
- More relevancy rules = a larger database. The `proximity` ranking rule alone is responsible for almost 80% of the database size. Faceting also consumes a large amount of disk space.

Thanks for bringing this to our attention, and I hope this helps in some small way!

**Comment by tobyglei** [comment]
> Hey @tobyglei , sorry for the delay in getting back to you. Truthfully this is not an easy question; disk size and RAM usage of the database depend on a large number of factors, including which relevancy rules you use, the languages in your dataset, the number of repeated words, whether or not you use faceting, the list goes on.
> 
> In the future we plan to provide thorough benchmarking with lots of different datasets, but that takes time, and isn't a priority for this engine since **we have an entirely new engine coming** that will change everything. In any case, here are a few general principles:
> 
> * Because MeiliSearch uses a memory map, the search speed is based on the ratio between RAM and database size. If you have very little RAM and a large database, search can become quite slow. On the other hand if you had equal RAM and database size, search would be almost instantaneous.
> * The number of CPU cores has a high impact on indexing speed—not much impact on search.
> * More relevancy rules = a larger database. The `proximity` ranking rule alone is responsible for almost 80% of the database size. Faceting also consumes a large amount of disk space.
> 
> Thanks for bringing this to our attention, and I hope this helps in some small way!

Hi @react-learner , I think the explanation you have is good enough. 
Hope to see something like this on MeiliSearch's documentation so when people ask, I can point them to read your docs. Maybe you guys put this on the FAQ section?
