### ISSUE TITLE
Add tech standards in the contributing documentation

### ISSUE THREAD

**Issue by fharper** [meilisearch/documentation#839]
Add the content of https://www.notion.so/meilisearch/Tech-Standards-b687256abfeb4d1889bc85290d0655d8 (private) to the contribution page/section of our doc.

**Comment by bidoubiwa** [comment]
After talking with @tpayet. The tech standards should not be replicated for the moment. So what we thought was to make the tech standards public on notion and link it in the documentation. Until we deem that it is accurate enough to not change every Sunday and in which case it could go 100% on the documentation.

**Comment by fharper** [comment]
I'm missing something here @tpayet. I mean, it's as we discussed about being open. We publish things are they are in the moment we publish them, and we update when needed, even if that means a lot of changes or making mistakes?

Also, just to be clear, the goal wasn't to duplicate them (I hate duplication): the goal was to put them there and delete the Notion page after. In a perfect world, we would have iterate them on a GitHub PR.

I'm writing this here for the sake of transparency, but I also contacted @tpayet directly so we can discuss about this :)

**Comment by tpayet** [comment]
I think we are on the same page as we want to avoid duplication here.

Charlotte wanted to add another week before moving tech standards from Notion to the documentation in order to be able to refine it if necessary in the coming days.

Let's move it as soon as someone can do it and let's ensure that at the same time the document will be deleted from Notion.

**Comment by fharper** [comment]
@react-learner will create a PR next week.
