### ISSUE TITLE
Clarify that we support a very large number of languages

### ISSUE THREAD

**Issue by fharper** [meilisearch/documentation#853]
In the [language reference](https://docs.meilisearch.com/reference/features/language.html#language), instead of `Any language that uses whitespace to separate words` (or under), let's list them all. It's a marketing thing, it's also adding languages that people can find if they search the doc to see if it's supported.

**Comment by react-learner** [comment]
I think this will be a veryyyyyy long list. It would be easier to give a list of languages that do not use whitespace to separate words (e.g. https://en.wikipedia.org/wiki/Category:Writing_systems_without_word_boundaries)

**Comment by fharper** [comment]
That is the goal. It is the different between we support 3+ languages and 100 as an example.

**Comment by dichotommy** [comment]
A list of all the languages we support would be too long, but we should still clarify the fact that we support many languages, and that we want users of any language to try the product and send us feedback. Since this is somewhat a difficult subject, I think we could add a brief FAQ to the languages.md file.

Something like: `My language doesn't use whitespace to separate words. Does that mean I can't use MeiliSearch?`
`Absolutely not! It just means that your experience may not be optimized. Many of our users work with non-Roman alphabets (e.g. Cyrillic, Thai, Japanese).`

`Does MeiliSearch plan to support additional languages in the future?`
`We would like to support as many languages as possible. The more feedback we get from native speakers, the easier it is for us to understand how to improve performance for those languages—and the more requests to improve support for a specific language, the more likely we are to devote resources to that project.`

**Comment by guimachiavelli** [comment]
Possibly jumping on a moving train here, but what is the difference between supporting a language or not in our case?

If I understand @dichotommy correctly, all languages work (as in, Meilisearch will display relevant search results in Farsi, Japanese and etc) and the difference lies in optimisation, so isn't `support` potentially misleading?

Hard agree on not having a list of every language in the world.

**Comment by dichotommy** [comment]
@guimachiavelli Good question. Basically, MeiliSearch will work to varying degrees of effectiveness with different languages. When we say "support", most of the time we're saying that we have a **specific tokenization pipeline** for that language or class of languages (in the case of white-space languages). You can read more about tokenization [here](https://docs.meilisearch.com/reference/under_the_hood/tokenization.html).

So, we know with confidence that MeiliSearch will work great for all languages that use space as a word separator (super easy to tokenize). Same for Chinese, since we have a Chinese-specific tokenizer. Everything else really depends on the language. In Japanese for example, most single kanji can be read as standalone words or as part of a larger compound word. Without a Japanese-specific tokenizer there's really no way to say, so as a result the relevancy really suffers.
