### ISSUE TITLE
Update references to `movies.json` and stopword files

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/documentation#954]
As @bidoubiwa mentioned, the `movies.json` dataset currently used in the Quick Start guide will be moved to `meilisearch/datasets`.

Options:
1. bring the file into the docs repo, which could make it easier to manage this file dependency;
2. link to the file in the new datasets repo, which would ensure we're always in line with the data used by core and integrations

Something to keep in mind: the datasets repo might also be temporary, as git is possibly not the place to store an 18MB json file.

Stopword files have already been moved, but there are no references to any of those in the docs.

**Comment by guimachiavelli** [comment]
For reference, these are the instances of `movies.json` on the current docs (2021-06-09):

```
learn/getting_started/quick_start.md, line #66
Below is an example to showcase how to add documents to an index called movies. To follow along, first right-click this link and download the file: [movies.json](https://raw.githubusercontent.com/meilisearch/MeiliSearch/master/datasets/movies/movies.json). Then, move the downloaded file to your working directory.
```

```
reference/under_the_hood/storage.md, line #55
We did some measurements on the default [movies.json](https://github.com/meilisearch/MeiliSearch/blob/master/datasets/movies/movies.json) dataset that you can find in the [getting started guide](notion://www.notion.so/learn/getting_started/quick_start.md#add-documents).
```

```
resources/faq.md, line #50
For now, we provide this [movies dataset](https://github.com/meilisearch/MeiliSearch/blob/master/datasets/movies/movies.json). More datasets are coming soon!
```

**Comment by bidoubiwa** [comment]
Options: 

After some investigation I understood that if we want to make `movies.json` downloadable, meaning, that if you click on it it does not open a new tab with the huge json as plain text, but it downloads it as `movies.json` in your system.

> bring the file into the docs repo, which could make it easier to manage this file dependency;

Makes movies.json downloadable. See above. 
Also. people will be able to access the file by going on this link: 

https://docs.meilisearch.com

> link to the file in the new datasets repo, which would ensure we're always in line with the data used by core and integrations

Makes movies.json not downloadable but centralises where the dataset is present and thus makes the update easier. 

> Something to keep in mind: the datasets repo might also be temporary, as git is possibly not the place to store an 18MB json file.

If we don't change the file too often it isn't a huge problem. Since commit storage could become 

[The limit for a file in git is 50MB](https://docs.github.com/en/github/managing-large-files/working-with-large-files/conditions-for-large-files)



Conclusion: 
For the moment I suggest we keep `movies.json` in the documentation. But we should find a solution on how we handle the update of `movies.json` as duplicating the hosts of movies.json makes it that we have to update it in every repo on change.
